name: Deploy Theme
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'ci:') && !contains(github.event.head_commit.message, 'chore:')"
    steps:
      - uses: actions/checkout@master
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16 # Do not update as ghost doesn't run on node 18
      - run: npm install && npm run zip
      - uses: TryGhost/action-deploy-theme@v1.4.1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          file: dist/lyra.zip
